### ISSUE TITLE
Access to dashboard template

### ISSUE THREAD

**Issue by Ubusubus** [google/pmax_best_practices_dashboard#1]
Heya.

How to get access to template dashboard? Atm it's not accessible.
https://datastudio.google.com/c/u/0/reporting/8ce3b94b-2dfe-48a0-b022-a22287bf00ff/page/i5YsC/

**Comment by DilshadTMI** [comment]
You can request access and Google will assign you access

**Comment by imosing** [comment]
@Ubusubus 

You're referring to the old template, please use the new one that's used in the workflow:

https://lookerstudio.google.com/c/u/0/reporting/6e773f65-7612-45af-af37-e3cab6a9828b/page/i5YsC
To access the template please follow the steps mentioned in the repo prerequisites (join the group).
